const S={STUDENTS:'Students',SNACKS:'Snacks',RELOADS:'Reloads',TX:'Transactions'};
function doGet(){setup_();return HtmlService.createTemplateFromFile('Index').evaluate().setTitle('FBLA Snack Pass').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}
function setup_(){const ss=SpreadsheetApp.getActive();mk_(ss,S.STUDENTS,['Student Barcode','Student Name','Grade','Opening Points','Active','Created At']);mk_(ss,S.SNACKS,['Snack Barcode','Snack Name','Point Cost','Unit Cost','Starting Quantity','Active','Created At']);mk_(ss,S.RELOADS,['Timestamp','Student Barcode','Student Name','Points Added','Amount Paid','Staff']);mk_(ss,S.TX,['Timestamp','Student Barcode','Student Name','Snack Barcode','Snack Name','Points Deducted','Balance Before','Balance After','Staff'])}
function mk_(ss,n,h){let s=ss.getSheetByName(n)||ss.insertSheet(n);if(!s.getLastRow()){s.getRange(1,1,1,h.length).setValues([h]).setFontWeight('bold').setBackground('#17365D').setFontColor('#fff');s.setFrozenRows(1)}}
function n_(v){return String(v==null?'':v).trim()}
function rows_(n){setup_();const s=SpreadsheetApp.getActive().getSheetByName(n);return s.getLastRow()<2?[]:s.getRange(2,1,s.getLastRow()-1,s.getLastColumn()).getDisplayValues()}
function student_(b){b=n_(b);for(const r of rows_(S.STUDENTS))if(n_(r[0])===b)return{barcode:r[0],name:r[1],grade:r[2],opening:+r[3]||0,active:String(r[4]).toLowerCase()!=='no'};return null}
function snack_(b){b=n_(b);for(const r of rows_(S.SNACKS))if(n_(r[0])===b)return{barcode:r[0],name:r[1],points:+r[2]||0,cost:r[3]===''?null:+r[3],qty:r[4]===''?null:+r[4],active:String(r[5]).toLowerCase()!=='no'};return null}
function balance_(b){const s=student_(b);if(!s)return null;let add=0,spent=0;rows_(S.RELOADS).forEach(r=>{if(n_(r[1])===n_(b))add+=+r[3]||0});rows_(S.TX).forEach(r=>{if(n_(r[1])===n_(b))spent+=+r[5]||0});return s.opening+add-spent}
function remaining_(b){const s=snack_(b);if(!s||s.qty===null)return null;let sold=0;rows_(S.TX).forEach(r=>{if(n_(r[3])===n_(b))sold++});return s.qty-sold}
function lookupStudent(b){const s=student_(b);if(!s)return{ok:false,message:'Student not found.'};if(!s.active)return{ok:false,message:'Student account is inactive.'};return{ok:true,student:{barcode:s.barcode,name:s.name,grade:s.grade,balance:balance_(b)}}}
function addStudent(d){const b=n_(d.barcode),name=n_(d.name),grade=n_(d.grade),opening=+d.opening||0;if(!b)throw Error('Scan the student ID first.');if(!name)throw Error('Enter the student name.');if(student_(b))throw Error('That barcode is already assigned.');SpreadsheetApp.getActive().getSheetByName(S.STUDENTS).appendRow([b,name,grade,opening,'Yes',new Date()]);return{message:name+' added with '+opening+' points.'}}
function loadPoints(d){const b=n_(d.barcode),p=+d.points,paid=+d.paid||0,staff=n_(d.staff),s=student_(b);if(!s)throw Error('Student not found.');if(!p||p<1)throw Error('Points must be greater than zero.');SpreadsheetApp.getActive().getSheetByName(S.RELOADS).appendRow([new Date(),b,s.name,p,paid,staff]);return{message:'Added '+p+' points to '+s.name+'.',balance:balance_(b)}}
function addSnack(d){const b=n_(d.barcode),name=n_(d.name),p=+d.points,cost=d.cost===''?'':+d.cost,qty=d.qty===''?'':+d.qty;if(!b)throw Error('Scan the snack barcode first.');if(!name)throw Error('Enter the snack name.');if(!p||p<1)throw Error('Point cost must be greater than zero.');if(snack_(b))throw Error('That snack barcode is already registered.');SpreadsheetApp.getActive().getSheetByName(S.SNACKS).appendRow([b,name,p,cost,qty,'Yes',new Date()]);return{message:name+' registered for '+p+' point'+(p===1?'':'s')+'.'}}
function checkout(d){setup_();const lock=LockService.getDocumentLock();lock.waitLock(5000);try{const sb=n_(d.studentBarcode),pb=n_(d.snackBarcode),staff=n_(d.staff),s=student_(sb),p=snack_(pb);if(!s)throw Error('Student not found.');if(!p)throw Error('Snack not found.');const before=balance_(sb),remain=remaining_(pb);if(remain!==null&&remain<=0)throw Error(p.name+' is out of stock.');if(before<p.points)throw Error(s.name+' only has '+before+' points.');const after=before-p.points;SpreadsheetApp.getActive().getSheetByName(S.TX).appendRow([new Date(),sb,s.name,pb,p.name,p.points,before,after,staff]);return{snack:p.name,points:p.points,balance:after}}finally{lock.releaseLock()}}
function dashboard(){const st=rows_(S.STUDENTS).filter(r=>n_(r[0])),sn=rows_(S.SNACKS).filter(r=>n_(r[0])),tx=rows_(S.TX);let o=0;st.forEach(r=>o+=balance_(r[0])||0);return{students:st.length,snacks:sn.length,sales:tx.length,points:o}}
function getStudents(){return rows_(S.STUDENTS).filter(r=>n_(r[0])).map(r=>({barcode:r[0],name:r[1],grade:r[2],balance:balance_(r[0])}))}
function getSnacks(){return rows_(S.SNACKS).filter(r=>n_(r[0])).map(r=>({barcode:r[0],name:r[1],points:+r[2]||0,remaining:remaining_(r[0])}))}
function getSales(){return rows_(S.TX).slice(-100).reverse().map(r=>({time:r[0],student:r[2],snack:r[4],points:r[5],balance:r[7],staff:r[8]}))}